# Tomcat
server:
  tomcat:
    uri-encoding: UTF-8
    max-threads: 1000
  port: 8080
  connection-timeout: 5000ms
  servlet:
     context-path: /baby

spring:
  # 环境 dev|test|prod
  profiles:
    active: dev
  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 100MB
      enabled: true
  aop:
    auto: true
    proxy-target-class: true
  mvc:
    throw-exception-if-no-handler-found: true
  application:
    name: grant-baby

#mybatis
mybatis-plus:
  mapper-locations: classpath*:/mapper/**/*.xml
  #实体扫描，多个package用逗号或者分号分隔
  typeAliasesPackage: com.graint.baby.code.modules.*.entity
  global-config:
    #数据库相关配置
    db-config:
      #主键类型  AUTO:"数据库ID自增", INPUT:"用户输入ID", ID_WORKER:"全局唯一ID (数字类型唯一ID)", UUID:"全局唯一ID UUID";
      id-type: ID_WORKER
      #字段策略 IGNORED:"忽略判断",NOT_NULL:"非 NULL 判断"),NOT_EMPTY:"非空判断"
      field-strategy: NOT_NULL
      #驼峰下划线转换
      column-underline: true
      logic-delete-value: -1
      logic-not-delete-value: 0
    banner: false
  #原生配置
  configuration:
    map-underscore-to-camel-case: true
    cache-enabled: false
    call-setters-on-nulls: true
    jdbc-type-for-null: 'null'
    # 关于mybatis的日志配置，参考官方文档<a href="https://mybatis.org/mybatis-3/zh/logging.html"/>
    # 注意：
    # 如果配置 org.apache.ibatis.logging.stdout.StdOutImpl，则在logback文件中配置打印SQL也不会打印到
    # 配置的日志中。
    # 除非将该配置注释掉，或者使用其他的日志打印
    log-impl: org.apache.ibatis.logging.log4j2.Log4j2Impl

#jwt配置
dhb:
  jwt:
    # 加密秘钥
    secret: f4e2e52034348f86b67cde581c0f9eb5
    # token有效时长，7天，单位秒
    expire: 604800
    header: token
logging:
  config: classpath:logback/logback-spring.xml